# This Dockerfile is used to build a custom Nginx Docker image that serves a static HTML page. It starts from the official Nginx base image and copies a custom index.html file into the appropriate directory for Nginx to serve.
FROM nginx:1.29-alpine
COPY index.html /usr/share/nginx/html