apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification
    app.kubernetes.io/component: service  
    app.kubernetes.io/owner: usermgmt-platform
  annotations:
    eks.amazonaws.com/pod-identity-association: "enabled"
