apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: usermgmt-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: usermgmt-platform

  ports:
    - name: http
      port: 8096
      targetPort: http