apiVersion: v1
kind: Service
metadata:
  name: usermgmt
  labels:
    app.kubernetes.io/name: usermgmt
    app.kubernetes.io/instance: usermgmt
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: usermgmt-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: usermgmt
    app.kubernetes.io/instance: usermgmt

  ports:
    - name: http
      port: 8095
      targetPort: http
      protocol: TCP